version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      POSTGRES_DB: srs_db
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data

  fastapi_app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /mnt/hdexterno:/mnt/hdexterno
    environment:
      - TZ=America/Sao_Paulo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - FIREBASE_SERVICE_ACCOUNT={"type":"service_account","project_id":"scammapi","private_key_id":"5a86f9cc92167a4117087cfc797d4b672330b223","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4GAqfzyeYpECc\n1fzyPpncVggH+eG6pVZ4wWOJDYYnhRmc6oVdR3TVUSGlbmmzrtOA4aJ0wx5S5nkN\nPSVSIGE0rRTYFt7IRttvUBD8kQRLB8aRmLacpl/UmPqGXEpv9WA0cFBBJ7lyMkW9\nYBXP4PB24287qp64OgTyW9QazRuZFLBRTWUSGlo6SMDNyuplfgQXgnuM0iY5hs1k\netr8YXphQzlx/q9FZQYgOKTZSZCh2zWzGEdxycGwOlNND87ggjg04dIO9z+vrL1+\nqw/DlATW/c5MHhc5pLyZXyoydPmd/bFQ2hnBZQf4ubypy3WgNHJOs/d0LOQGAWhK\nmIFmk0LRAgMBAAECggEAUwXkpLXT8a8BxLls3gMFeK0D6jTzbC1slgEBVqnWurP4\nHSBXDP5Q3nM8bVMiMHrDv/gCQA5O+qweI65Tynn33L3CDMIjrsbl54mAX6c2/G+B\nSeBJWtRdm49yTG4K0/shbATK7NdxduLdOM7Ah4O2bqebXplQA12HJZXsTjn6HErG\n4/b1b4r3a/sXWyC30UY8qCelRq8UScgC250yjyXR50RpJ68kaXFgoevAskmVyv4N\ny+36/v60V6eOwJ0RmTrFDf55qN1jB6fiOG+xofXGukbPZ7LWh6+w6X8CpWczM5/F\ns+7tIdqXKStzGNK66GRgN5ouK4aIpdGHjkK+fN9zkQKBgQD2izMI9GoBclGI+A1m\nJH18Xp7CSUM9wyBL77+lBJCzYJRY6HAx23tbrKcXH9Rl3XL2HGEHFw9KLeDTEA6c\nC6Lq/Pe+yXF1kKLoLc9c7xahbJ5O8dF0fh25rxWLCo1yj4vEJU1L7sNM6L7kazES\nPq1sbIuO6NCFuTvJ/emAOg5B+wKBgQC/J6Z9vFRwjrVlcdIAaIP18gSxwpo2Ko65\naaThQV2shgzwBffZDC34TqrJtrxLd9c2h2d4gd0eYQVb/zt0QhLV0kRL9VM95kNL\nfax1P+XXIg2mGZh9xyY0e8Rn/ubu74PTtTGJdZMiy38fBi7z93tgafMkWJki2BmE\n8L9ivZnAowKBgQCppY8wkj5/UFKalVVi+6j9c3564j7KuQH4Prj4q/OF+ucZZpgN\nNqHjqyIu31Af6Am7IDwDzPJQcNFLarki1z77w6YWOjdAVo5ChYMyx7Ii0cL9P5iJ\nOF7r7nY8fr5mHjBmf+R4Y4sv2NfCBaB2lXpwKSC+7aTO328sxvNtsIUvEQKBgESd\n0gjOYq0ovPqWOeDFo6DUaFT62upYqnTp9DKbiSmV0O0T51z1H0dDzdCslLiuYwWC\n42SBkUMHZqoYW1onIaW5XaS6gk/06PEfQpmv/ywTYDzgcTmtFAzA5MbD3FemiHal\nUwvZtaBG1fHoAVC35IS+Y3YHi6jTU43B8aFbF+brAoGBAIUerI3JkQiXTeaq+LtH\nnf5HHhh2OOs5xqZvdSPi609rWQOtQYhfbNcauCa7Rk+aDHS0Hm3uM+gm/RaM4ODq\n3ue4X0bkSBDPxOOmbnuGasTzTPG26Bkg76bQ5L0AC6wQgUwYlO+bVPV/bAv6xIRy\nkTkMzvQOsdh2LFDtxTPNIVqb\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-fbsvc@scammapi.iam.gserviceaccount.com","client_id":"115154652175393598625","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40scammapi.iam.gserviceaccount.com","universe_domain":"googleapis.com"}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - TZ=America/Sao_Paulo
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - default

volumes:
  redis_data:
