version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: scamm_api
    restart: always
    ports:
      - "4200:4200"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - ENVIRONMENT=production
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./models:/app/models
      - ./middleware:/app/middleware
      - ./database:/app/database
      - ./cache:/app/cache
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - scamm_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:alpine
    container_name: scamm_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - scamm_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  scamm_network:
    driver: bridge

volumes:
  redis_data:
    driver: local 